version: '3.8'

volumes:
  pg_data:

services:
  postgres:
    container_name: utility-bills-reader-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: utility-bills-reader
      PGDATA: /data/postgres
    volumes:
      - pg_data:/data/postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: utility-bills-reader-api
    command: npm run start:dev
    environment:
      - PORT=${PORT:-3333}
    ports:
      - '3333:3333'
    depends_on:
      - postgres
    volumes:
      - ./:/app
